/* Auto generated file by build command shell.
    !!!!!!!! Do not edit this file. !!!!!!!!
    Created time : 2011. 08. 16. (화) 15:30:26 KST
    Created by chero@pantech.com (GS1 Team)
*/
#ifndef BOARD_REV_H
#define BOARD_REV_H

/*
Current MODEL ID is T_J_MASAI_E 
LINUX Kernel Define & macro function is as follows
#define CONFIG_MACH_MSM8X55_J_MASAI_E
machine_is_msm8x55_j_masai_e() function
*/

#define PT10  0x0001
#define PT20  0x0004
#define WS10 0x0010
#define WS11 0x0020
#define WS20 0x0040
#define ES10  0x0100
#define ES20  0x0400
#define TP10  0x1000
#define TP20  0x4000

#define BOARD_VER   TP10
#endif /*BOARD_REV_H*/
